#!/bin/sh

GPIB_CONFIG_OPTIONS="--minor 0"

PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
HOME=/root
export HOME PATH

if [ -x /usr/bin/logger ]; then
        /usr/bin/logger -t $0 "entered for Product: $PRODUCT Device: $DEVICE Serial: $SERIAL Devpath: $DEVPATH"
fi 

# Multi-board with serial numbers
# Uncomment and edit the code below to setup the serial numbers and minors
# that correspond to your system.
#
#case $SERIAL in
#    N0000001) GPIB_CONFIG_OPTIONS="--minor 0"
#	      ;;
#    N0000002) GPIB_CONFIG_OPTIONS="--minor 1"
#	      ;;
#esac
#

# Multi-board with device path
# Uncomment and edit the code below to setup the device paths and minors
# that correspond to your system.
#
#case $DEVPATH in
#    */usb2/2-1) GPIB_CONFIG_OPTIONS="--minor 0"
#	      ;;
#    */usb2/2-2) GPIB_CONFIG_OPTIONS="--minor 1"
#	      ;;
#esac
#

gpib_config $GPIB_CONFIG_OPTIONS --sysfs-device-path $DEVPATH

