#!/bin/bash
#
# This script is used to configure the gpib package
#
[ -z "$BASH" ] && { echo "Configure requires bash" 1>&2; exit 1; }

# Disable filename globbing once and for all.
# Enable function cacheing.
set -f -h

clear 

DIALOG=0

if hash dialog ; then
	DIALOG=$(hash -t dialog)
elif hash whiptail ; then
	DIALOG=$(hash -t whiptail)
fi

if [ $DIALOG == 0 ] ; then
  echo
  echo "Could not find 'dialog' or 'whiptail' programs."
  echo "Please install one of them."
  echo 
  echo "See the INSTALL and README files."
  echo
exit 1
fi

function set_var() {
	echo "$1=$2" >>$CONFIG
	echo "#define $1 ($2)" >>$CONFIG_H
	eval "$1=$2"
}

function set_svar() {
	echo "$1=\"$2\"" >>$CONFIG
	echo "#define $1 \"$2\"" >>$CONFIG_H
	eval "$1=$2"
}


case $1 in 
######################################################################
--test)

. ./Setup.test

exit 0
;;
######################################################################
*)

. ./Setup.in

exit 0
;;
######################################################################

esac
