/* This file will be generated by config */
/*           DONT EDIT !!!!              */
#undef NIAT 
#undef NIPCII 
#undef NIPCIIa 
#undef HP82335 
#undef ZIATECH 
#undef CBI_4882 
#undef CBI_PCI 
#undef CBI_PCMCIA 
#undef MODBUS_PCI 
#undef INES_PCI 
#undef INES_PCMCIA 
#define NIPCII 
#define CBI_4882 
