######################################################################
#
#   Makefile for the gpib tcl extension
#   (C) C.Schroeter clausi@chemie.fu-berlin.de
#
#####################################################################

#####################################################################
# 
# The Path where your GPIB stuff lives
# This is normally set by the toplevel Makefile
#
GPIB_HOME = `(cd ../../../ ; pwd)`



clean: 
	rm -f *.bak *.dat* *~

